version: '3'
services:
  docker-api:
    build:
      args:
        NODE_ENV: stagging
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env.stagging
    command: npm run stagging