version: '3'
services:
  docker-api:
    build:
      args:
        NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env.production
    command: npm run prod
